# Codemagic YAML — Build APK only

workflows:
  build-apk:
    name: Build APK
    max_build_duration: 60
    environment:
      flutter: stable
      java: "17"
    scripts:
      - name: Get packages
        script: |
          flutter pub get
      - name: Build APK (Release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - darksoulzx34@gmail.com
        notify_on_build:
          success: true
          failure: true